# Generated by Django 6.0.7 on 2026-09-06 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_add_offered_status'),
        ('jobs', '0005_jobbookmark'),
        ('resume_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateResumeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=255, verbose_name='Candidate Name')),
                ('chunk_type', models.CharField(choices=[('WORK_EXPERIENCE', 'Work Experience'), ('SKILLS_SUMMARY', 'Skills and Summary'), ('PROJECT', 'Project'), ('EDUCATION_CERTIFICATIONS', 'Education and Certifications')], db_index=True, max_length=32, verbose_name='Chunk Type')),
                ('content', models.TextField(verbose_name='Chunk Content')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Chunk Metadata')),
                ('embedding', models.JSONField(blank=True, default=list, verbose_name='Embedding Vector')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_chunks', to='applications.application')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_resume_chunks', to='jobs.job')),
                ('resume_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='resume_analysis.resumeanalysisrecord')),
            ],
            options={
                'verbose_name': 'Candidate Resume Chunk',
                'verbose_name_plural': 'Candidate Resume Chunks',
                'ordering': ['application', 'id'],
                'indexes': [models.Index(fields=['job', 'chunk_type'], name='rag_job_chunk_type_idx'), models.Index(fields=['application', 'chunk_type'], name='rag_app_chunk_type_idx')],
            },
        ),
    ]
