# Generated by Django 6.0.7 on 2026-08-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('SHORTLISTED', 'Shortlisted'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', max_length=20, verbose_name='Status'),
        ),
    ]
