# Generated by Django 6.0.7 on 2026-09-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_add_offered_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rejection_note',
            field=models.TextField(blank=True, verbose_name='Rejection note'),
        ),
    ]
