# Generated by Django 6.0.7 on 2026-09-20 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_rejection_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255, verbose_name='Offer Position Title')),
                ('base_salary', models.CharField(max_length=120, verbose_name='Base Salary / Compensation')),
                ('bonus', models.CharField(blank=True, max_length=120, verbose_name='Signing / Performance Bonus')),
                ('equity', models.CharField(blank=True, max_length=120, verbose_name='Stock Grants / Equity')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Anticipated Start Date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Offer Expiration Date')),
                ('additional_terms', models.TextField(blank=True, verbose_name='Benefits, Relocation & Terms')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20, verbose_name='Offer Status')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='applications.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
