# Generated by Django 6.0.7 on 2026-09-05 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_add_offered_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('overall_score', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True, verbose_name='Overall Score')),
                ('recommendation', models.CharField(blank=True, max_length=30, verbose_name='Recommendation')),
                ('structured_resume', models.JSONField(blank=True, default=dict, verbose_name='Structured Resume')),
                ('evaluation_scorecard', models.JSONField(blank=True, default=dict, verbose_name='Evaluation Scorecard')),
                ('raw_text', models.TextField(blank=True, verbose_name='Raw Resume Text')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analysis', to='applications.application')),
            ],
            options={
                'verbose_name': 'Resume Analysis Record',
                'verbose_name_plural': 'Resume Analysis Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
