# Generated by Django 6.0.7 on 2026-08-17 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employerprofile_seekerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Resume Title')),
                ('file', models.FileField(upload_to='resumes/%Y/%m/', verbose_name='Resume File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='users.seekerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
