# Generated by Django 6.0.7 on 2026-09-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-is_primary', '-created_at']},
        ),
        migrations.AddField(
            model_name='resume',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Is Primary'),
        ),
    ]
