# Generated by Django 6.0.7 on 2026-09-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_resume_options_resume_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Company Size'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Founded Year'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='headquarters',
            field=models.CharField(blank=True, max_length=255, verbose_name='Headquarters Location'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='Logo URL'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='perks',
            field=models.JSONField(blank=True, default=list, verbose_name='Company Perks & Culture'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='social_linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='social_twitter',
            field=models.URLField(blank=True, verbose_name='Twitter/X URL'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company Tagline'),
        ),
    ]
