# Generated by Django 6.0.7 on 2026-09-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employerprofile_company_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='education',
            field=models.JSONField(blank=True, default=list, verbose_name='Education History'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='experience',
            field=models.JSONField(blank=True, default=list, verbose_name='Work Experience Timeline'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Professional Headline'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Current Location'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='projects',
            field=models.JSONField(blank=True, default=list, verbose_name='Project Showcase'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, verbose_name='Core Skills'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='Developer & Social Links'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Years of Experience'),
        ),
    ]
