# Generated by Django 6.0.7 on 2026-08-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_employe_9a6de3_idx',
            old_name='jobs_job_employe_6f0f57_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_status_277b31_idx',
            old_name='jobs_job_status__0a3fb0_idx',
        ),
    ]
