# Generated by Django 6.0.7 on 2026-08-19 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_jobs_job_employe_6f0f57_idx_jobs_job_employe_9a6de3_idx_and_more'),
        ('users', '0003_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=255, verbose_name='Keyword')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('employment_type', models.CharField(blank=True, choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('TEMPORARY', 'Temporary'), ('FREELANCE', 'Freelance')], max_length=20, verbose_name='Employment type')),
                ('minimum_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Minimum salary')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='DAILY', max_length=10, verbose_name='Alert frequency')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Last sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to='users.seekerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seeker', 'is_active'], name='jobs_jobale_seeker__4af834_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='users.seekerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('seeker', 'job'), name='jobs_saved_job_seeker_job_unique')],
            },
        ),
    ]
