# Generated by Django 6.0.7 on 2026-09-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='Benefits and perks'),
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('ENTRY_LEVEL', 'Entry Level'), ('MID_LEVEL', 'Mid Level'), ('SENIOR', 'Senior'), ('LEAD', 'Lead / Staff'), ('EXECUTIVE', 'Executive')], default='MID_LEVEL', max_length=20, verbose_name='Experience level'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='Requirements and qualifications'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, verbose_name='Key responsibilities'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.JSONField(blank=True, default=list, verbose_name='Required skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='workplace_type',
            field=models.CharField(choices=[('ON_SITE', 'On-site'), ('HYBRID', 'Hybrid'), ('REMOTE', 'Remote')], default='ON_SITE', max_length=20, verbose_name='Workplace type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('TEMPORARY', 'Temporary'), ('FREELANCE', 'Freelance')], default='FULL_TIME', max_length=20, verbose_name='Employment type'),
        ),
    ]
