# Generated by Django 6.0.7 on 2026-09-05 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0005_jobbookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights_used', models.JSONField(default=dict, verbose_name='Weights Used')),
                ('ranked_candidates', models.JSONField(default=list, help_text='List of ranked candidate objects with criterion scores, final score, and reasons', verbose_name='Ranked Candidates')),
                ('total_candidates', models.PositiveIntegerField(default=0, verbose_name='Total Candidates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_snapshots', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Ranking Snapshot',
                'verbose_name_plural': 'Job Ranking Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.JSONField(default=dict, help_text="Dictionary of criterion name to weight (e.g. {'experience': 0.5, 'skills': 0.5})", verbose_name='Scoring Weights')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_config', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Scoring Config',
                'verbose_name_plural': 'Job Scoring Configs',
            },
        ),
    ]
