# Generated by Django 6.0.7 on 2026-09-05 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_add_offered_status'),
        ('jobs', '0005_jobbookmark'),
        ('resume_screening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateScreeningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structured_resume', models.JSONField(blank=True, help_text='Cached JSON output of StructuredResume from Phase 1', null=True, verbose_name='Structured Resume')),
                ('resume_file_name', models.CharField(blank=True, max_length=255, verbose_name='Resume File Name')),
                ('criteria_evaluations', models.JSONField(default=dict, help_text='Cached dictionary of criterion evaluations: {criterion: {score, reason}}', verbose_name='Criteria Evaluations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_record', to='applications.application')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_records', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Candidate Screening Record',
                'verbose_name_plural': 'Candidate Screening Records',
            },
        ),
    ]
