# Generated by Django 6.0.7 on 2026-09-05 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0005_jobbookmark'),
        ('users', '0004_alter_resume_options_resume_is_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Session Title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_sessions', to='users.employerprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_sessions', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Copilot Session',
                'verbose_name_plural': 'Copilot Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CopilotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System')], default='USER', max_length=15, verbose_name='Role')),
                ('content', models.TextField(verbose_name='Content')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='recruiter_copilot.copilotsession')),
            ],
            options={
                'verbose_name': 'Copilot Message',
                'verbose_name_plural': 'Copilot Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
